version: '3'

services:
  nginx:
    image: nginx:1.19.0-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx.default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    links:
      - php:php
      - mysql:mysql
    networks:
      - laravel-project

  mysql:
    image: mysql:8.0.20
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_username
      MYSQL_PASSWORD: test_password
      MYSQL_ROOT_PASSWORD: test_password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data/:/var/lib/mysql
    networks:
      - laravel-project

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel-project

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel-project

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel-project

  npm:
    image: node:14.5.0-alpine
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  git:
    image: alpine/git:v2.26.2
    container_name: git
    volumes:
      - ./src:/git

networks:
  laravel-project: